#!/bin/sh
# initramfs hook: include i2cset and i2c modules for early VOFF setting
set -e
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/i2cset /usr/sbin
manual_add_modules i2c_bcm2835 i2c_dev i2c_brcmstb
