/**
 * TypeScript types matching device-side configuration files.
 * These are used when the cloud dashboard renders device config info
 * received via telemetry or API calls.
 */

// ── uconsole.conf (INI file) ─────────────────────────────

/** Maps to [device] section of /etc/uconsole/uconsole.conf */
export interface DeviceSection {
  /** Device hostname, defaults to "uconsole" */
  hostname: string;
  /** Expansion module type. "auto" probes at boot. */
  expansion_module: "auto" | "none" | "4g" | "aio-v1" | "aio-v2";
  /** WiFi backend. "auto" picks NetworkManager if available, else dhcpcd. */
  wifi_method: "auto" | "networkmanager" | "dhcpcd";
}

/** Maps to [webdash] section of /etc/uconsole/uconsole.conf */
export interface WebdashSection {
  /** Whether the local web dashboard is enabled */
  enabled: boolean;
  /** Port for the Flask backend (default 8080, nginx proxies 443→here) */
  port: number;
  /** Bind address for Flask (default "127.0.0.1") */
  bind: string;
  /** Path to SSL certificate used by nginx (default "/etc/uconsole/ssl/uconsole.crt") */
  ssl_cert: string;
  /** Path to SSL key used by nginx (default "/etc/uconsole/ssl/uconsole.key") */
  ssl_key: string;
}

/** Maps to [cloud] section of /etc/uconsole/uconsole.conf */
export interface CloudSection {
  /** Whether cloud telemetry push is enabled */
  enabled: boolean;
  /** Push interval in seconds (default 300 = 5 minutes) */
  push_interval: number;
  /** Cloud API base URL (default "https://uconsole.cloud") */
  api_url: string;
}

/** Maps to [backup] section of /etc/uconsole/uconsole.conf */
export interface BackupSection {
  /** Whether automated backups are enabled */
  enabled: boolean;
  /** Backup schedule */
  schedule: "daily" | "weekly" | "manual";
  /** Time of day for scheduled backups (HH:MM, 24h format) */
  time: string;
  /** Comma-separated list of backup categories (e.g. "shell,system,packages,browser") */
  categories: string;
}

/** Maps to [power] section of /etc/uconsole/uconsole.conf — SAFETY-CRITICAL, read-only in cloud */
export interface PowerSection {
  /** CPU frequency cap in MHz (0 = no cap) */
  cpu_freq_cap: number;
  /** Low battery auto-shutdown threshold in millivolts */
  low_battery_shutdown: number;
  /** Charge current limit in milliamps */
  charge_current: number;
}

/** Full system config — maps to /etc/uconsole/uconsole.conf */
export interface UconsoleSystemConfig {
  device: DeviceSection;
  webdash: WebdashSection;
  cloud: CloudSection;
  backup: BackupSection;
  power: PowerSection;
}

// ── config.json (user preferences) ───────────────────────

/** Maps to ~/.config/uconsole/config.json */
export interface UconsoleUserConfig {
  /** TUI color theme name (e.g. "default", "hacker", "solarized") */
  theme: string;
  /** TUI view mode */
  view_mode: string;
  /** Battery gauge style in TUI (e.g. "bar", "donut", "numeric") */
  battery_gauge: string;
  /** Whether to show AIO expansion panels in TUI (false if no AIO board) */
  show_aio_panels: boolean;
  /** bcrypt hash of webdash password */
  webdash_password_hash: string;
  /** bcrypt hash of hotspot password */
  hotspot_password_hash: string;
  /** SSID for WiFi fallback AP (default "uConsole") */
  hotspot_ssid: string;
  /** Cloud device token (UUID v4) — stored in status.env, referenced here */
  cloud_token: string;
  /** Linked cloud repo in "owner/repo" format */
  cloud_repo: string;
}

// ── hardware.json (hardware manifest) ────────────────────

/** A single detected hardware component */
export interface HardwareComponent {
  /** Whether the component was detected at scan time */
  detected: boolean;
  /** Device path (e.g. "/dev/spidev4.0", "/dev/ttyS0") — present when detected */
  device?: string;
  /** Chip/model identifier (e.g. "RTL2838", "SX1262") — present when detected */
  chip?: string;
  /** Sysfs or device path used for detection */
  path?: string;
  /** Human-readable reason when not detected (e.g. "no USB device matching 0bda:2838") */
  reason?: string;
}

/** GPS-specific component with fix status */
export interface GpsComponent extends HardwareComponent {
  /** Whether GPS has a satellite fix — only meaningful when detected */
  has_fix?: boolean;
}

/** ESP32 sensor node component */
export interface Esp32Component extends HardwareComponent {
  /** Serial port path (e.g. "/dev/ttyUSB0") */
  port?: string;
  /** Firmware version reported by the ESP32 */
  firmware?: string;
}

/** Maps to /etc/uconsole/hardware.json — generated by `uconsole setup` hardware scan */
export interface HardwareManifest {
  /** Expansion module type detected (e.g. "aio-v1", "none") */
  expansion: string;
  /** RTL-SDR radio receiver */
  sdr: HardwareComponent;
  /** LoRa SX1262 transceiver */
  lora: HardwareComponent;
  /** GPS/GNSS receiver */
  gps: GpsComponent;
  /** Real-time clock */
  rtc: HardwareComponent;
  /** ESP32 sensor node (optional external module) */
  esp32: Esp32Component;
  /** WiFi management method detected (e.g. "networkmanager", "dhcpcd") */
  wifi_method: string;
  /** Compute module identifier (e.g. "CM4", "CM4S") */
  compute_module: string;
  /** Running kernel version */
  kernel: string;
  /** OS description (e.g. "Debian GNU/Linux 12 (bookworm)") */
  os: string;
  /** ISO 8601 timestamp of when hardware scan was performed */
  detected_at: string;
}
