const GITHUB_API = "https://api.github.com";
const GITHUB_RAW = "https://raw.githubusercontent.com";

export class GitHubError extends Error {
  constructor(
    public status: number,
    message: string
  ) {
    super(message);
    this.name = "GitHubError";
  }
}

async function githubFetch(
  url: string,
  token: string,
  isJson = true
): Promise<unknown | null> {
  const res = await fetch(url, {
    headers: {
      Authorization: `token ${token}`,
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "uconsole-cloud",
    },
    next: { revalidate: 60 },
  });
  if (res.status === 401) throw new GitHubError(401, "GitHub token expired");
  if (res.status === 403) throw new GitHubError(403, "GitHub rate limit exceeded");
  if (!res.ok) return null;
  return isJson ? res.json() : res.text();
}

export async function fetchRepoInfo(
  token: string,
  repo: string
) {
  return githubFetch(`${GITHUB_API}/repos/${repo}`, token);
}

export async function fetchCommits(
  token: string,
  repo: string,
  perPage = 50
) {
  return githubFetch(
    `${GITHUB_API}/repos/${repo}/commits?per_page=${perPage}`,
    token
  );
}

export async function fetchTree(
  token: string,
  repo: string,
  branch = "main"
) {
  return githubFetch(
    `${GITHUB_API}/repos/${repo}/git/trees/${branch}`,
    token
  );
}

export async function fetchRawFile(
  token: string,
  repo: string,
  path: string,
  branch = "main"
): Promise<string | null> {
  return githubFetch(
    `${GITHUB_RAW}/${repo}/${branch}/${path}`,
    token,
    false
  ) as Promise<string | null>;
}

const PACKAGE_FILES: Record<string, string> = {
  APT: "packages/apt-manual.txt",
  Flatpak: "packages/flatpak.txt",
  Snap: "packages/snap.txt",
  Cargo: "packages/cargo.txt",
  pip: "packages/pip-user.txt",
  ClockworkPi: "packages/clockworkpi.txt",
};

export async function fetchAllPackages(
  token: string,
  repo: string
): Promise<Record<string, string[]>> {
  const entries = Object.entries(PACKAGE_FILES);
  const results = await Promise.all(
    entries.map(([, path]) => fetchRawFile(token, repo, path))
  );

  const packages: Record<string, string[]> = {};
  entries.forEach(([manager], i) => {
    const text = results[i];
    packages[manager] = text
      ? text
          .split("\n")
          .map((l) => l.trim())
          .filter((l) => l && !l.startsWith("#"))
      : [];
  });
  return packages;
}

export async function fetchExtensions(
  token: string,
  repo: string
): Promise<string[]> {
  const text = await fetchRawFile(token, repo, "config/chromium/extensions.txt");
  if (!text) return [];
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
}

export async function fetchScriptsManifest(
  token: string,
  repo: string
): Promise<string | null> {
  return fetchRawFile(token, repo, "scripts/scripts-manifest.txt");
}

export async function fetchCommitDetail(
  token: string,
  repo: string,
  sha: string
): Promise<{
  sha: string;
  stats: { total: number; additions: number; deletions: number };
  files: {
    filename: string;
    status: string;
    additions: number;
    deletions: number;
  }[];
} | null> {
  const data = (await githubFetch(
    `${GITHUB_API}/repos/${repo}/commits/${sha}`,
    token
  )) as {
    sha: string;
    stats: { total: number; additions: number; deletions: number };
    files: {
      filename: string;
      status: string;
      additions: number;
      deletions: number;
    }[];
  } | null;
  if (!data) return null;
  return {
    sha: data.sha,
    stats: data.stats,
    files: (data.files ?? []).map((f) => ({
      filename: f.filename,
      status: f.status,
      additions: f.additions,
      deletions: f.deletions,
    })),
  };
}

export async function validateUconsoleRepo(
  token: string,
  repo: string
): Promise<boolean> {
  const apt = await fetchRawFile(token, repo, "packages/apt-manual.txt");
  return apt !== null;
}

// ── GitHub Write API ────────────────────────────────────

async function githubPost(
  url: string,
  token: string,
  body: unknown
): Promise<{ status: number; data: Record<string, unknown> }> {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `token ${token}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      "User-Agent": "uconsole-cloud",
    },
    body: JSON.stringify(body),
  });
  const data = await res.json();
  return { status: res.status, data };
}

const BOOTSTRAP_FILES: { path: string; content: string }[] = [
  {
    path: "packages/apt-manual.txt",
    content: "# Manually installed APT packages\n# Generated by uconsole backup\n",
  },
  {
    path: "packages/flatpak.txt",
    content: "# Flatpak packages\n",
  },
  {
    path: "packages/snap.txt",
    content: "# Snap packages\n",
  },
  {
    path: "packages/cargo.txt",
    content: "# Cargo packages\n",
  },
  {
    path: "packages/pip-user.txt",
    content: "# pip user packages\n",
  },
  {
    path: "packages/clockworkpi.txt",
    content: "# ClockworkPi packages\n",
  },
  {
    path: "scripts/push-status.sh",
    content:
      "#!/bin/bash\n# Push device status to uconsole.cloud\n# This script is managed by 'uconsole setup'\n# Run 'uconsole update' to get the latest version\necho \"Run 'uconsole update' to download the full script\"\n",
  },
  {
    path: "scripts/backup.sh",
    content:
      "#!/bin/bash\n# uConsole backup script\n# Run 'uconsole update' to get the latest version\necho \"Backup script placeholder — run 'uconsole update' for the full version\"\n",
  },
  {
    path: "restore.sh",
    content:
      "#!/bin/bash\n# uConsole restore script\n# This will be populated after your first backup\necho \"No backup data yet. Run backup.sh on your device first.\"\n",
  },
  {
    path: "README.md",
    content:
      "# uConsole Backup\n\nAutomated backup repository for [uConsole](https://www.clockworkpi.com/uconsole) device configuration.\n\nManaged by [uconsole.cloud](https://uconsole.cloud).\n\n## Setup\n\n```bash\ncurl -fsSL https://uconsole.cloud/install | bash\nuconsole setup\n```\n\n## Structure\n\n- `packages/` — Package manifests (apt, flatpak, snap, cargo, pip)\n- `scripts/` — Backup and status scripts\n- `restore.sh` — System restore script\n",
  },
  {
    path: ".gitignore",
    content: ".env\n*.log\n.DS_Store\nnode_modules/\n",
  },
];

export async function createBootstrapRepo(
  token: string,
  name: string,
  isPrivate: boolean
): Promise<{ full_name: string } | { error: string }> {
  // 1. Create the repo
  const create = await githubPost(`${GITHUB_API}/user/repos`, token, {
    name,
    description: "uConsole backup — managed by uconsole.cloud",
    private: isPrivate,
    auto_init: false,
  });

  if (create.status === 422) {
    return { error: "Repository name already exists" };
  }
  if (create.status !== 201) {
    return { error: `Failed to create repository (${create.status})` };
  }

  const fullName = create.data.full_name as string;
  const [owner, repoName] = fullName.split("/");

  try {
    // 2. Create blobs
    const blobShas: { path: string; sha: string }[] = [];
    for (const file of BOOTSTRAP_FILES) {
      const blob = await githubPost(
        `${GITHUB_API}/repos/${owner}/${repoName}/git/blobs`,
        token,
        { content: file.content, encoding: "utf-8" }
      );
      if (blob.status !== 201) {
        throw new Error(`Failed to create blob for ${file.path}`);
      }
      blobShas.push({ path: file.path, sha: blob.data.sha as string });
    }

    // 3. Create tree
    const tree = await githubPost(
      `${GITHUB_API}/repos/${owner}/${repoName}/git/trees`,
      token,
      {
        tree: blobShas.map((b) => ({
          path: b.path,
          mode: "100644",
          type: "blob",
          sha: b.sha,
        })),
      }
    );
    if (tree.status !== 201) {
      throw new Error("Failed to create tree");
    }

    // 4. Create commit
    const commit = await githubPost(
      `${GITHUB_API}/repos/${owner}/${repoName}/git/commits`,
      token,
      {
        message: "Initial uconsole backup structure",
        tree: tree.data.sha,
      }
    );
    if (commit.status !== 201) {
      throw new Error("Failed to create commit");
    }

    // 5. Create main ref
    const ref = await githubPost(
      `${GITHUB_API}/repos/${owner}/${repoName}/git/refs`,
      token,
      { ref: "refs/heads/main", sha: commit.data.sha }
    );
    if (ref.status !== 201) {
      throw new Error("Failed to create ref");
    }

    return { full_name: fullName };
  } catch {
    // Cleanup: delete the empty repo on failure
    await fetch(`${GITHUB_API}/repos/${owner}/${repoName}`, {
      method: "DELETE",
      headers: {
        Authorization: `token ${token}`,
        "User-Agent": "uconsole-cloud",
      },
    });
    return { error: "Failed to initialize repository. Please try again." };
  }
}

export async function fetchGitHubUser(
  token: string
): Promise<{ login: string } | null> {
  const data = await githubFetch(`${GITHUB_API}/user`, token);
  if (!data || typeof data !== "object") return null;
  return { login: (data as { login: string }).login };
}
